version: '3.8'

services:
  personal-page:
    build: .
    image: ${REGISTRY}personal-page
    restart: always
    ports:
      - 8080
    networks:
      - web
    labels:
      - traefik.http.routers.todos.rule=Host(`${REMOTE:-localhost}`)
      - traefik.docker.network=web

networks:
  web:
    external: true
